### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by rashmipankaj** [Azure-Samples/docker-django-webapp-linux#6]
I cloned this repository and created a docker image pushed to azure container registry. I created a web app for containers based on this ACR image. Once I am trying to browse the website it gives error as Service Unavailable

**Comment by jikuma** [comment]
use linux machine to build the image. Hosted linux if you are using VSTS. The machine behind running azure webapp is linux.

**Comment by joshdavies89** [comment]
Did you manage to resolve this issue? I'm having the same problem and i've spent far too long trying to resolve. Keeps telling me the image doesn't exist on my Docker Hub :(

**Comment by jikuma** [comment]
@joshdavies89 what is your base image. Is it linux based?.

**Comment by lioneltrebuchon** [comment]
@jikuma jikuma, yes in my case it is linux based, and I have the same problem.
In my case, it's because I cannot build (`docker build`).
It seems like the debian repos it's searching for don't exist anymore, or in any case pinging them doesn't work ( http://deb.debian.org/debian/dists/stretch-updates/InRelease and deb.debian.org:80 ).

I do not know what I should set in the Dockerfile (or somewhere else?) to solve that problem...

Here the error:
 ```
Unable to connect to deb.debian.org:http: [IP: 149.20.4.15 80]
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Could not connect to prod.debian.map.fastly.net:80 (151.101.112.204). - connect (111: Connection refused) Could not connect to deb.debian.org:80 (149.20.4.15). - connect (111: Connection refused) [IP: 149.20.4.15 80]
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Could not connect to prod.debian.map.fastly.net:80 (151.101.12.204). - connect (111: Connection refused) Could not connect to security.debian.org:80 (212.211.132.250). - connect (111: Connection refused) [IP: 212.211.132.250 80]
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Unable to connect to deb.debian.org:http: [IP: 149.20.4.15 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by FlipWebApps** [comment]
@lioneltrebuchon I had similar issues when trying to build within our corporate network, but built fine though from a more open connection without proxy, ssl interception and other things coming into play so might be worth trying that if you haven't do so already
